services:

  auth-ms-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - auth

  auth-ms:
    build: ./Dockerfile
    depends_on:
      - ms_auth_db
    networks:
      - auth
      - tadsbank
