version: '3.8'

networks:
  tadsbank:
  auth:
  cliente:
  conta:
  gerente:

services:
  frontend-app:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: tadsbank-frontend
    ports:
      - "4200:80"

  auth-ms-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - auth

  auth-ms:
    build: .back-end/MS_Auth/Dockerfile
    depends_on:
      - auth-ms-db
    environment:
      JWT_SECRET: AYqQdMQcnW6JOCMyBS24A8GFbeRk4VTth6o8FlSDNIs
    volumes:
      - ./src:/app/src
    command: mvn spring-boot:run
    networks:
      - auth
      - tadsbank

  gateway:
    build: ./back-end/API_Gateway/Dockerfile
    networks:
      - tadsbank

