server:
  port: 4873

spring:
  application:
    name: conta
  rabbitmq:
    template:
      reply-timeout: 30
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/ms_contas
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver #
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE