spring.application.name=auth
server.port=8055

spring.rabbitmq.host=tadsbank
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.data.mongodb.uri=mongodb://auth:27017/ms_auth

security.jwt.secret-key=${JWT_SECRET}
security.jwt.expiration-time=864000000