spring.application.name=auth
server.port=8055

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

security.jwt.secret-key=${JWT_SECRET}
security.jwt.expiration-time=864000000